spring:
  application:
    name: recipe-backend

  datasource:
    url: jdbc:mysql://localhost:3306/jsw?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    open-in-view: false

  redis:
    host: localhost
    port: 6379
logging.level:
  #org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secret: aG9uZ2RhZXN0dWR5MTAwMHJlY2VpcGViYWNrZW5kdG9rZW4=
  access-token-valid-seconds: 7200 # 2 hour
  refresh-token-valid-seconds: 604800 # 7 day
