spring:
  application:
    name: recipe-backend

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secret: aG9uZ2RhZXN0dWR5MTAwMHJlY2VpcGViYWNrZW5kdG9rZW4=
  access-token-valid-seconds: 7200 # 2 hour
  refresh-token-valid-seconds: 604800 # 7 day
